apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: bastion.vuong.com.hpemsp.local:5000/myproject/dockersamples-examplevotingapp_result:before 
      #dockersamples/examplevotingapp_result:before
        name: result
        ports:
        - containerPort: 80
          name: result
