apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: bastion.vuong.com.hpemsp.local:5000/myproject/dockersamples-examplevotingapp_worker:latest #dockersamples/examplevotingapp_worker
        name: worker
